language: php
 
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache
 
before_script:
  - composer install --prefer-dist --no-interaction --dev
 
script: ./vendor/bin/phpunit
